### ISSUE TITLE
Link from openaustralia.org.au -> TVFY not working

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#1072] opened 2015-10-13 07:33 UTC
For example on page:
http://www.openaustralia.org.au/senator/mitch_fifield/victoria

Clicking link "Hardly ever rebels against their party in this parliament."

goes to 
https://theyvoteforyou.org.au/mp.php?id=uk.org.publicwhip/member/100083#divisions

which should redirect to something else but doesn't. That makes me sad.

**Comment by henare** [comment] 2015-10-13 07:35
Thanks for logging this @mlandauer.

>That makes me sad.

Me too.

Closing as a duplicate of #1053.

**Closed by henare** 2015-10-13 07:35 UTC

**Comment by henare** [comment] 2016-03-17 06:40
Fixed by @novemberkilo :metal:
