### ISSUE TITLE
enable cross-origin resource sharing on the JSON API

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/publicwhip#1052] opened 2015-02-23 00:48 UTC
This would also people to more simply use the JSON api without JSONP.

> Cross-Origin Resource Sharing (CORS) is a specification that enables truly open access across domain-boundaries. If you serve public content, please consider using CORS to open it up for universal JavaScript/browser access.

See http://enable-cors.org/

There's information about setting this up on the server on http://enable-cors.org/server.html

> For simple CORS requests, the server only needs to add the following header to its response:
> 
> `Access-Control-Allow-Origin: *`
> 
> There are some more headers and settings involved if you want to support verbs other than GET/POST, custom headers, or authentication. You can learn more about these options in the Using CORS tutorial on HTML5 Rocks.

**Comment by equivalentideas** [comment] 2015-02-23 21:56
Looks like we could use this gem https://github.com/cyu/rack-cors

**Comment by mlandauer** [comment] 2020-06-29 01:42
Duplicate of #1222

**Closed** 2020-06-29 02:22 UTC
Labels: enhancement, good for first contribution
