### ISSUE TITLE
multiples of one person shown in search results

### ISSUE THREAD

**Issue by katska** [openaustralia/publicwhip#1404] opened 2022-04-07 03:26 UTC
for example:

3 x Craig Kelly returned. They're all the same as far as I can tell.
https://theyvoteforyou.org.au/search?utf8=✓&query=Craig+kelly&button=Submit

<img width="1086" alt="Screen Shot 2022-04-07 at 1 14 40 pm" src="https://user-images.githubusercontent.com/1001129/162114074-81d75e45-bc05-4df5-8302-c3f50d624d93.png">

x 2 Andrew Wilkies https://theyvoteforyou.org.au/search?query=Andrew+wilkie&button=Search

**Comment by mlandauer** [comment] 2022-04-07 03:28
Duplicate of #1259

**Closed by mlandauer** 2022-04-07 03:28 UTC
Labels: bug
