### ISSUE TITLE
When I'm looking at a policy I'm interested in, help me see how my MP voted on it when I don't know their name or face

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/publicwhip#1121] opened 2017-02-21 04:18 UTC
How does someone find out how their mp voted on a specific policy when they don't know what they look like?

For example, someone sees a link to a policy page on facebook and clicks on it. They read the description and wonder how their MP is voting on it, but they don't know who there MP is.

**Comment by henare** [comment] 2017-02-21 04:40
Duplicate of #1091 I think.

**Closed by henare** 2017-02-21 04:40 UTC
Labels: design

**Comment by equivalentideas** [comment] 2017-02-21 04:42
> Duplicate of #1091 I think.

Agreed. I'm going to rename that issue cause I think this personal story issue name format is more helpful than one that describes a solution.
