### ISSUE TITLE
Bronwyn Bishop appears twice on this list

### ISSUE THREAD

**Issue by SimonBiggs** [openaustralia/publicwhip#1068] opened 2015-09-14 22:32 UTC
https://theyvoteforyou.org.au/people/representatives/wentworth/malcolm_turnbull/friends

Leads to he being incorrectly placed at 100%.

**Comment by henare** [comment] 2015-09-14 22:35
Thanks for spotting this. It's something to do with the way people "change party" when they become speaker... >waves hands<

**Comment by equivalentideas** [comment] 2016-02-25 05:50
Closing this as a duplicate of new well documented version #1082

**Closed by equivalentideas** 2016-02-25 05:50 UTC
Labels: bug
