### ISSUE TITLE
postcode 4271 not working on TVFY search

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1243] opened 2021-05-21 01:57 UTC
We have been emailed to inform us that when searching postcode 4271 on TVFY, no results are found. It should bring up Wright MP [Scott Buchholz](https://theyvoteforyou.org.au/people/representatives/wright/scott_buchholz).

**Comment by mlandauer** [comment] 2021-12-15 00:24
I think I'll just close this as a duplicate of #1197

**Closed by mlandauer** 2021-12-15 00:24 UTC
Labels: bug, search
